import {
  avatarTones,
  breakpoints,
  colors,
  containers,
  desktop,
  dimens,
  easing,
  fontFamily,
  fontWeights,
  iconSize,
  motion,
  radii,
  shadows,
  space,
  typography,
} from './tokens.ts';
import type { ThemeName } from './tokens.ts';

const kebab = (s: string): string => s.replace(/[A-Z]/g, (c) => `-${c.toLowerCase()}`);
const px = (n: number): string => `${n}px`;
const rem = (n: number): string => `${+(n / 16).toFixed(5)}rem`;
const ms = (n: number): string => `${n}ms`;

const declare = (entries: Array<[string, string]>, indent = '  '): string =>
  entries.map(([k, v]) => `${indent}${k}: ${v};`).join('\n');

function themeBlock(theme: ThemeName): string {
  const entries: Array<[string, string]> = [];
  for (const [key, value] of Object.entries(colors[theme])) {
    entries.push([`--color-${kebab(key)}`, value]);
  }
  avatarTones[theme].forEach((tone, i) => {
    entries.push([`--avatar-${i}-bg`, tone.bg], [`--avatar-${i}-fg`, tone.fg]);
  });
  entries.push(['--shadow-menu', shadows[theme].menu], ['--shadow-dialog', shadows[theme].dialog]);
  entries.push(['color-scheme', theme]);
  return declare(entries);
}

function sharedBlock(): string {
  const e: Array<[string, string]> = [];
  for (const [k, v] of Object.entries(space)) e.push([`--space-${kebab(k)}`, px(v)]);
  for (const [k, v] of Object.entries(radii)) e.push([`--radius-${kebab(k)}`, px(v)]);
  for (const [k, v] of Object.entries(iconSize)) e.push([`--icon-size-${kebab(k)}`, px(v)]);
  for (const [k, v] of Object.entries(motion)) e.push([`--motion-${kebab(k)}`, ms(v)]);
  for (const [k, v] of Object.entries(easing)) e.push([`--ease-${kebab(k)}`, v]);
  for (const [k, v] of Object.entries(dimens)) e.push([`--dimen-${kebab(k)}`, px(v)]);

  e.push(['--desktop-control-height', px(desktop.controlHeight)]);
  e.push(['--desktop-row-height-wide', px(desktop.rowHeightWide)]);
  e.push(['--desktop-sidebar-width-laptop', px(desktop.sidebarWidth.laptop)]);
  e.push(['--desktop-sidebar-width-desktop', px(desktop.sidebarWidth.desktop)]);
  e.push(['--desktop-sidebar-width-wide', px(desktop.sidebarWidth.wide)]);
  e.push(['--desktop-sidebar-rail-width', px(desktop.sidebarRailWidth)]);
  e.push(['--desktop-search-max-width', px(desktop.searchMaxWidth)]);
  e.push(['--desktop-drawer-width', px(desktop.drawerWidth)]);
  e.push(['--desktop-row-sender-width', px(desktop.rowSenderWidth)]);

  // Documentation only: breakpoints are consumed in JS. Exposed so they are inspectable.
  for (const [k, v] of Object.entries(breakpoints)) e.push([`--breakpoint-${k}`, px(v)]);
  e.push(['--container-list-wide', px(containers.listWide)]);

  e.push(['--font-family-sans', fontFamily]);
  for (const [k, v] of Object.entries(fontWeights)) e.push([`--font-weight-${k}`, String(v)]);
  for (const [name, role] of Object.entries(typography)) {
    const line = +(role.line / role.size).toFixed(4);
    e.push([`--font-${kebab(name)}`, `${role.weight} ${rem(role.size)}/${line} var(--font-family-sans)`]);
    const tracking = 'tracking' in role ? role.tracking : 0;
    e.push([`--tracking-${kebab(name)}`, `${+(tracking / role.size).toFixed(4)}em`]);
  }

  // web adaptation: interaction state layers derived from existing tokens (no new colors).
  e.push(
    ['--state-hover', 'color-mix(in srgb, var(--color-text-primary) 6%, transparent)'],
    ['--state-pressed', 'color-mix(in srgb, var(--color-text-primary) 10%, transparent)'],
    ['--state-hover-on-app-bar', 'color-mix(in srgb, var(--color-on-app-bar) 14%, transparent)'],
    ['--state-pressed-on-app-bar', 'color-mix(in srgb, var(--color-on-app-bar) 22%, transparent)'],
    ['--focus-ring', '2px solid var(--color-accent)'],
    ['--focus-ring-on-app-bar', '2px solid var(--color-on-app-bar)'],
  );
  return declare(e);
}

/** Generates the complete tokens.css. Dark is the default (mobile: AppThemeMode.dark). */
export function generateCss(): string {
  return `/* GENERATED by packages/tokens/scripts/generate-css.ts — do not edit. Source: src/tokens.ts */

:root {
${sharedBlock()}
}

:root,
[data-theme='dark'] {
${themeBlock('dark')}
}

[data-theme='light'] {
${themeBlock('light')}
}

@media (prefers-reduced-motion: reduce) {
  :root {
${Object.keys(motion)
  .map((k) => `    --motion-${kebab(k)}: 0ms;`)
  .join('\n')}
  }
}
`;
}
